#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
main() {
	tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
	trap 'rm "$tmpfile"' 0 1 15
	sed -n "w $tmpfile"
	sed -i 's/\x0//g' "$tmpfile"
	ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
	chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu_custom -p "Copy which command's output?" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
	eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
    if [ "${1,,}" = "--out-only" ] ; then
	    awk "/^$chosen$/{p=1;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
    else
	    awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
    fi
}

main "${@}"
